// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnWoSrCiJhbL7K3hxMlCjnufGka5lehMA',
    appId: '1:998015983382:web:60d1d34cd86c87510dba37',
    messagingSenderId: '998015983382',
    projectId: 'togetherdo-45834',
    authDomain: 'togetherdo-45834.firebaseapp.com',
    storageBucket: 'togetherdo-45834.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA99vfjlJjN32u0kD-zLGhvFZX8AWgIqyU',
    appId: '1:998015983382:android:38fc675f7621f8ad0dba37',
    messagingSenderId: '998015983382',
    projectId: 'togetherdo-45834',
    storageBucket: 'togetherdo-45834.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0Yrw2j1BUHUTEt88Kc0NsvKBy2MSWqkY',
    appId: '1:998015983382:ios:21ad705daad682b10dba37',
    messagingSenderId: '998015983382',
    projectId: 'togetherdo-45834',
    storageBucket: 'togetherdo-45834.firebasestorage.app',
    iosBundleId: 'com.example.mpmaAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0Yrw2j1BUHUTEt88Kc0NsvKBy2MSWqkY',
    appId: '1:998015983382:ios:21ad705daad682b10dba37',
    messagingSenderId: '998015983382',
    projectId: 'togetherdo-45834',
    storageBucket: 'togetherdo-45834.firebasestorage.app',
    iosBundleId: 'com.example.mpmaAssignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnWoSrCiJhbL7K3hxMlCjnufGka5lehMA',
    appId: '1:998015983382:web:6a0030b8261871e00dba37',
    messagingSenderId: '998015983382',
    projectId: 'togetherdo-45834',
    authDomain: 'togetherdo-45834.firebaseapp.com',
    storageBucket: 'togetherdo-45834.firebasestorage.app',
  );
}
